### ISSUE TITLE
 话题列表显示创建时间功能Bug - linuxdo.js

### ISSUE THREAD

**Issue by AITIAN-GH** [dlzmoe/linuxdo-scripts#1]
![cap](https://github.com/user-attachments/assets/1cee49e0-2935-4fa5-a911-b367b5837993)

打开"话题列表显示创建时间"功能，在切换到Linux Do某一 "标签" 并 "筛选最新" 

列表中出现上图情况，列表中小图标无法正确加载一直闪烁，控制台一直打印请求https://linux.do/uploads/default/original/3X/0/a/0a7634b834bc6ecef03ab57306dafd8475387155.png
出错，导致Chrome占用cpu 直至100% 系统卡死

Chrome 版本 127.0.6533.89

linuxdo.js 版本 0.0.27

**Comment by dlzmoe** [comment]
收到反馈~

**Comment by dlzmoe** [comment]
https://github.com/dlzmoe/linuxdo-scripts/releases/tag/0.1.2

新版本已修复这个问题。
