### ISSUE TITLE
fork了本仓库，使用vite-plugin-monekey构建了一版，保证兼容性，正在调试……

### ISSUE THREAD

**Issue by xifan2333** [dlzmoe/linuxdo-scripts#14]
调试完毕，正常使用无误后，发 pr 给您可以吗？

**Comment by dlzmoe** [comment]
可以先提个pr  没什么问题就可以合并

**Comment by dlzmoe** [comment]
@xifan2333 你好，方便的话可以加下联系方式，细聊 vite-plugin-monekey 重构的问题吗，我也有这个打算

邮箱 anghunk@gmail.com，可以发wx号给我

**Comment by xifan2333** [comment]
> @xifan2333 你好，方便的话可以加下联系方式，细聊 vite-plugin-monekey 重构的问题吗，我也有这个打算
> 
> 邮箱 [anghunk@gmail.com](mailto:anghunk@gmail.com)，可以发wx号给我

今天在忙别的，晚上发现你已经重构完了，私信了wechat，后续如果能贡献代码再联系。
