### ISSUE TITLE
gpt配置好之后，请求报错跨域

### ISSUE THREAD

**Issue by wzj1223** [dlzmoe/linuxdo-scripts#16]
如题

**Comment by dlzmoe** [comment]
具体使用方法可以描述一下，以及相关截图，报错，脚本管理器使用方法

如果是使用引入第三方文件是会有跨域的，这个解决不了

现在支持的是点击文件安装

**Comment by dlzmoe** [comment]
暂不支持 http ，有没有这个原因

**Comment by wzj1223** [comment]
> 暂不支持 http ，有没有这个原因

啥意思？

**Comment by dlzmoe** [comment]
@wzj1223 你用的 baseurl 链接不支持 http 网址

**Comment by wzj1223** [comment]
https://linux.do/t/topic/187568   
就是这个帖子中的，你可以看下 @dlzmoe

**Comment by dlzmoe** [comment]
> https://linux.do/t/topic/187568 就是这个帖子中的，你可以看下 @dlzmoe

api 本身就是有问题的。。跟功能无关
如果发现报错，可以先试试其他平台是否可以使用

![image](https://github.com/user-attachments/assets/78946ef4-eaa7-447e-833a-ca5b5bee2f1f)
