### ISSUE TITLE
墓碑图片无法正常加载

### ISSUE THREAD

**Issue by wisokey** [dlzmoe/linuxdo-scripts#17]
墓碑的图片可否直接使用Linux do站点的cdn，而不是第三方的cdn以避免无法加载图片的问题，像这样
![image](https://github.com/user-attachments/assets/ecda739c-136a-4c1a-bd41-25b787da752a)
利用Linux do站点的cdn应该也比较简单，新建一个帖子，然后把图片拖入编辑区域应该就能得到一个指向图片的链接。

**Comment by dlzmoe** [comment]
ok的

**Comment by wisokey** [comment]
我刚刚试了下，搞到了一个论坛的图片链接
https://linux.do/uploads/default/original/3X/b/d/bdf4a2ff2b3639c4f74462f2da8383f9c5cdb25e.png
