### ISSUE TITLE
创建时间显示错误

### ISSUE THREAD

**Issue by ryan961** [dlzmoe/linuxdo-scripts#18]
**描述错误**
对错误内容的清晰简洁的描述。

**复现步骤**
1. ... 
2. ...
3. ...

**版本说明**
产生错误时使用的插件版本/浏览器/油猴管理器，比如：
0.3.4 / chrome / 暴力猴

**截图**
如果可以的话，尽量提供一些错误截图，比如控制台报错。
![image](https://github.com/user-attachments/assets/ce82debb-6727-4a12-a1b8-bec984b33250)
![image](https://github.com/user-attachments/assets/19ed6416-f24e-4116-8df0-6b1c0113c19a)

**Comment by dlzmoe** [comment]
新版本已修复这个问题
