### ISSUE TITLE
AI 总结支持 Dark 深色主题

### ISSUE THREAD

**Issue by dalefengs** [dlzmoe/linuxdo-scripts#19]
![image](https://github.com/user-attachments/assets/9c12807e-0979-4bd0-9c17-4e9f2ed86cb1)

有时候有点刺眼

**Comment by dlzmoe** [comment]
可以，下个版本会进行UI优化

**Comment by dalefengs** [comment]
辛苦大佬！太强了

**Comment by dlzmoe** [comment]
0.3.14 版本已更新

**Comment by dalefengs** [comment]
![image](https://github.com/user-attachments/assets/975b1081-9693-4423-b09d-65ac3d974f00)

可以可以！
