### ISSUE TITLE
【功能请求】建议新增时间过滤功能

### ISSUE THREAD

**Issue by jimu98** [dlzmoe/linuxdo-scripts#21]
可以增加一个过滤不看【xx】天之前的帖子。这样很方便使用

**Comment by jimu98** [comment]
> 可以增加一个过滤不看【xx】天之前的帖子。这样很方便使用

我指的是直接把这个帖子的元素移除，当然极端情况可能出现帖子过少的情况

**Comment by dlzmoe** [comment]
个人这个功能感觉实用性不高，对首页信息流影响很大，先待定了

**Comment by dlzmoe** [comment]
0.3.27
-新增：屏蔽指定天数前及指定分类的帖子
