### ISSUE TITLE
【错误报告】混排优化 bug

### ISSUE THREAD

**Issue by QAbot-zh** [dlzmoe/linuxdo-scripts#30]
**描述错误**
图文混排中，`![xxx](xxxx)` 格式会裂开

**版本说明**
产生错误时使用的插件版本/浏览器/油猴管理器，比如：
0.3.30 / chrome / 篡改猴

**截图**

![image](https://github.com/user-attachments/assets/36bdcd66-d67f-428f-a361-db3601ce400d)

![image](https://github.com/user-attachments/assets/8556b0e0-89ab-4a6f-90da-34f3a5299831)

**Comment by dlzmoe** [comment]
依赖库不太支持，我想办法绕 过markdown 语法也很有限

暂时没有特别好的解决办法，遇到markdown的图片写法可以换行，不会触发排版优化
