### ISSUE TITLE
【错误报告】ai操作http提示ssl error

### ISSUE THREAD

**Issue by shuangmuaigwu** [dlzmoe/linuxdo-scripts#31]
**描述错误**
对错误内容的清晰简洁的描述。

**版本说明**
产生错误时使用的插件版本/浏览器/油猴管理器，比如：
0.0.1 / chrome / 暴力猴
chrome 插件为最新版本使用暴力猴管理

**截图**
如果可以的话，尽量提供一些错误截图，比如控制台报错或者页面。
<img width="389" alt="image" src="https://github.com/user-attachments/assets/015601d8-241e-405b-af1d-444690d8511a">

**Comment by dlzmoe** [comment]
暂时不支持ip形式的前缀
