### ISSUE TITLE
【功能请求】中秋小兔兔

### ISSUE THREAD

**Issue by googleweb** [dlzmoe/linuxdo-scripts#33]
我也想要有中秋小兔兔，添加功能，假装自己也有小兔兔，自己页面，个人资料卡等地方也能显示。

**Comment by dlzmoe** [comment]
只要发月饼贴就可以直接领取啦，在用户个人资料中

![image](https://github.com/user-attachments/assets/7f1b8947-e968-4277-96c8-8721543a32d3)

**Comment by googleweb** [comment]
我已经收到您的信件!
