### ISSUE TITLE
【功能请求】禁用选中分享功能

### ISSUE THREAD

**Issue by lx32056127** [dlzmoe/linuxdo-scripts#35]
提出你的创意和功能想法，如果有参考的实现方法可以贴上链接。
选中内容后会弹出引用和分享功能,能不能把这个分享功能禁用掉.  经常选中后误点

![图片](https://github.com/user-attachments/assets/031b1bcd-ee89-48c8-92f1-ec3ed5d36212)

**Comment by dlzmoe** [comment]
下个版本将会支持
