### ISSUE TITLE
【功能请求】添加自动随机浏览功能

### ISSUE THREAD

**Issue by iFoxox** [dlzmoe/linuxdo-scripts#36]
能不能加自动浏览功能
如插件：https://greasyfork.org/zh-CN/scripts/490382-%E8%87%AA%E5%8A%A8%E6%B5%8F%E8%A7%88linux-do-autobrowse-linux-do

**Comment by dlzmoe** [comment]
暂时不考虑这个功能，对我来说这个功能有点怪怪的
对于自动浏览目前已经有自动阅读功能了，有些冲突
后面可能会加上随机进入帖子
