### ISSUE TITLE
【错误报告】获取用户等级错误

### ISSUE THREAD

**Issue by iFoxox** [dlzmoe/linuxdo-scripts#37]
**描述错误**
查询等级时一直没有返回，控制台出错

**版本说明**
产生错误时使用的插件版本/浏览器/油猴管理器，比如：
0.3.35 / edge / 篡改猴
<img width="522" alt="image" src="https://github.com/user-attachments/assets/5471827f-8003-4d16-a65b-9d2f5171a142">

<img width="869" alt="image" src="https://github.com/user-attachments/assets/00e2ce3e-e0b6-49f8-b941-443ad32ce4a5">

**Comment by dlzmoe** [comment]
试了一下可以吖

![image](https://github.com/user-attachments/assets/14778b8c-7f09-4e5a-ac97-c92e9a65bf1c)

**Comment by wb-hwang** [comment]
天数错误：
![image](https://github.com/user-attachments/assets/06b0dfd7-3fcb-47fc-b2f9-f9abd8cc420c)![image](https://github.com/user-attachments/assets/84668596-20e6-4b82-bbae-6fde5c8fec77)

**Comment by dlzmoe** [comment]
> 天数错误： ![image](https://private-user-images.githubusercontent.com/8444080/367476633-06b0dfd7-3fcb-47fc-b2f9-f9abd8cc420c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzYxMTQsIm5iZiI6MTcyNjI3NTgxNCwicGF0aCI6Ii84NDQ0MDgwLzM2NzQ3NjYzMy0wNmIwZGZkNy0zZmNiLTQ3ZmMtYjJmOS1mOWFiZDhjYzQyMGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMDEwMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTk5YTFjZDg5OTc0YWVjMjI5ZWEyNzFmNTUyNTIxN2RiZWI1MjAzNzFjZTNlYTYxMTRkMGM5ZWYxZjQ1MzMxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xMoizhZy-IEJGSphqS5lPQmHB--F4QON5geiK4t5Xek)![image](https://private-user-images.githubusercontent.com/8444080/367476607-84668596-20e6-4b82-bbae-6fde5c8fec77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzYxMTQsIm5iZiI6MTcyNjI3NTgxNCwicGF0aCI6Ii84NDQ0MDgwLzM2NzQ3NjYwNy04NDY2ODU5Ni0yMGU2LTRiODItYmJhZS02ZmRlNWM4ZmVjNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTRUMDEwMzM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTE0ZWU4NDA2NDViOWJlZmYyNGUzZjdlOTQzMmY2OTBhZTQ0MGQwZWJkN2MyM2M4NDkwMmI2NDUxNTJiNjg4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._MguOiGZNo-tDuW2rGf8a4g5CymA-6o4_rGHeXcdSXo)

之前我发现这个问题，接口输出的天数跟 contact 可能会有差异，很奇怪，大概差个1-2天，没找到合适的解决办法，因为数据差距不大，就没有修复这个问题（其实是不知道怎么修复）

**Comment by wb-hwang** [comment]
我知道怎么修复。。。发个贴，附上issus 链接 @始皇 修复，顺便骗两分

**Comment by dlzmoe** [comment]
> 我知道怎么修复。。。发个贴，附上issus 链接 @始皇 修复，顺便骗两分

伤害转移大法哈哈，后面我再研究下这个问题

**Comment by iFoxox** [comment]
> 试了一下可以吖
> 
> ![image](https://private-user-images.githubusercontent.com/65840178/367475907-14778b8c-7f09-4e5a-ac97-c92e9a65bf1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzY1NTUsIm5iZiI6MTcyNjI3NjI1NSwicGF0aCI6Ii82NTg0MDE3OC8zNjc0NzU5MDctMTQ3NzhiOGMtN2YwOS00ZTVhLWFjOTctYzkyZTlhNjViZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Y2Y5OTkxYThlNGY0Mjc4NzA3NTg0OWYxZGYyM2NjN2Y2YTY4NzdiZmM2ODUxMjcxZDhjZmMxMzFkY2VkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJLPRnEZQZsLvOsNKMct_XpqaJvDkVEQ3WCPSwNJtRY)

有可能是因为我是第一天注册的原因，今天就可以了

**Comment by wb-hwang** [comment]
没法啊，要是接口问题你也处理不了，总不能说模拟一下请求抓html 的数据吧

> > 我知道怎么修复。。。发个贴，附上issus 链接 @始皇 修复，顺便骗两分
> 
> 伤害转移大法哈哈，后面我再研究下这个问题

**Comment by dlzmoe** [comment]
> 没法啊，要是接口问题你也处理不了，总不能说模拟一下请求抓html 的数据吧
> 
> > > 我知道怎么修复。。。发个贴，附上issus 链接 @始皇 修复，顺便骗两分
> > 
> > 
> > 伤害转移大法哈哈，后面我再研究下这个问题

其实也不是不行，fetch 一下 contact页面，然后抓取关键数据，嫌麻烦，你要是感兴趣的话，可以重写下这块的逻辑提交 pr  😎

**Comment by dlzmoe** [comment]
> > 试了一下可以吖
> > ![image](https://private-user-images.githubusercontent.com/65840178/367475907-14778b8c-7f09-4e5a-ac97-c92e9a65bf1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNzY1NTUsIm5iZiI6MTcyNjI3NjI1NSwicGF0aCI6Ii82NTg0MDE3OC8zNjc0NzU5MDctMTQ3NzhiOGMtN2YwOS00ZTVhLWFjOTctYzkyZTlhNjViZjFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDAxMTA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3Y2Y5OTkxYThlNGY0Mjc4NzA3NTg0OWYxZGYyM2NjN2Y2YTY4NzdiZmM2ODUxMjcxZDhjZmMxMzFkY2VkNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FJLPRnEZQZsLvOsNKMct_XpqaJvDkVEQ3WCPSwNJtRY)
> 
> 有可能是因为我是第一天注册的原因，今天就可以了

你这么一说我想起来了，之前也遇到过，好像因为没到一级的成员接口也查不到数据才报错，这个属于不可抗力，估计neo还没把数据入库
