### ISSUE TITLE
【错误报告】等级查询-访问天数 数据差距原因

### ISSUE THREAD

**Issue by wb-hwang** [dlzmoe/linuxdo-scripts#38]
**描述错误**
数据与connect 不一致。
我这边找到原因了，connect 的``访问天数``实际上是阅读天数，如果你那天阅读量为0 ，是不计入这个时间的。而你的接口用的``days_visited`` 是有登录网址的时间，两者是有区别的。我的数据里面，``50-49=1`` 的差距就是下面这条数据。

![image](https://github.com/user-attachments/assets/b7cd23b6-f7e2-4a8e-b4e8-a0e10c87d610)

这个数据在https://linux.do/u/xxx/summary 这里其实是有的，但是论坛的取值应该是取反了：
![image](https://github.com/user-attachments/assets/d8fe6cf5-5fef-4c00-9b12-634eaacb4fa5)

另外，上面获取数据的路径是：``偏好数据-导出您的数据``

**Comment by dlzmoe** [comment]
可以的，我修复一下，应该是需要对数据做一下计算

**Comment by wb-hwang** [comment]
论坛的数据应该也有问题，等我发个帖子水两分

**Comment by dlzmoe** [comment]
也不太对，阅读时间跟访问天数无关，看不出来相关关系，而且我的contact显示67，个人资料显示69，阅读时间4
69-67=2

我在找其他关联关系

**Comment by wb-hwang** [comment]
那个阅读时间我不知道是怎么来的，你导出一下你的数据看看，在visit.cvs 那里筛选一下没阅读的天数

**Comment by dlzmoe** [comment]
> 那个阅读时间我不知道是怎么来的，你导出一下你的数据看看，在visit.cvs 那里筛选一下没阅读的天数

确实，在visit.cvs中有两天为0，但是这个数据在接口中没有表现出来

**Comment by wb-hwang** [comment]
那没救了，按论坛里的讨论，阅读时间是将阅读的分钟数（或者秒）加起来得到的。跟这个数据没关系，只能等始皇加字段或者通过我们上个issus 说的模拟请求一下connect。

**Comment by dlzmoe** [comment]
> 那没救了，按论坛里的讨论，阅读时间是将阅读的分钟数（或者秒）加起来得到的。跟这个数据没关系，只能等始皇加字段或者通过我们上个issus 说的模拟请求一下connect。

哈哈 其实也不算什么大问题，这个功能本身就是辅助计算的，差的不多就行

**Comment by wb-hwang** [comment]
达成共识
```我也懒得修改了 😎```
