### ISSUE TITLE
【功能请求】AI的API地址完全自定义

### ISSUE THREAD

**Issue by 906051999** [dlzmoe/linuxdo-scripts#40]
目前自定义的部分只有baseurl，对于其他LLM的支持不是很好。
免费模型提供商如：智谱AI、SiliconCloud（硅基流动），请求后缀与openAI并不相同
增加一个自定义项：full_url即可，可以根据情况自行设置，减少适配难度

- openAI请求后缀：/v1/chat/completions

- 智谱AI的请求地址
- https://open.bigmodel.cn/api/paas/v4/chat/completions
- https://open.bigmodel.cn/dev/api/http-call/http-auth

在本地测试成功

**Comment by dlzmoe** [comment]
下个版本会适配下

**Comment by dlzmoe** [comment]
@906051999 0.3.44 版本更新该功能 

![image](https://github.com/user-attachments/assets/b3bd731d-04dc-4ca3-844c-fb7714baf047)

**Comment by 906051999** [comment]
感谢，已用上，辛苦了
