### ISSUE TITLE
【功能请求】Webdav的密码目前是明文显示

### ISSUE THREAD

**Issue by suomedualc** [dlzmoe/linuxdo-scripts#41]
Webdav的密码目前是明文显示，是否有考虑使用如password类型等方式隐藏一下

**Comment by dlzmoe** [comment]
也可以，主要都是在本地，包括备份也是自己手里，当时没考虑隐藏，既然有人提出来了，可以完善一下

**Comment by dlzmoe** [comment]
0.3.35 更新该功能。
