### ISSUE TITLE
【功能请求】关键词屏蔽功能是否可以忽略大小写

### ISSUE THREAD

**Issue by sephiroth233** [dlzmoe/linuxdo-scripts#42]
如题，目前是区分大小写的
![image](https://github.com/user-attachments/assets/170bcb6f-74ad-418e-b422-d2ae339678b9)

**Comment by dlzmoe** [comment]
就是想严谨一点，专门做了大小写区分，不然怕忽略掉用户不想忽略的内容

**Comment by sephiroth233** [comment]
好的，收到
