### ISSUE TITLE
【功能请求】建议整合关闭楼中楼回复在主贴下显示的功能

### ISSUE THREAD

**Issue by BearD01001** [dlzmoe/linuxdo-scripts#43]
https://linux.do/t/topic/40715/6

楼中楼回复在主贴中二次显示，上下文不明确，竟然令人感觉莫名其妙，建议整个这个油猴脚本的功能

**Comment by dlzmoe** [comment]
说实话，论坛回复这块的逻辑很复杂，我没把握搞定。
如果采用帖子内那种方式会有个问题，父子级关系的评论没有同时加载时会漏掉后者，偶发性的bug，没找到修复的方法。
最好的方法还是 neo 亲自动工修改论坛源码，插件难以完美控制，索性就不做这块的增强了。
