### ISSUE TITLE
【错误报告】插件导致文本框频繁触发账号密码填充

### ISSUE THREAD

**Issue by QAbot-zh** [dlzmoe/linuxdo-scripts#44]
**描述错误**

今天发现，插件会导致论坛的文本框频繁触发账号密码填充

**版本说明**
产生错误时使用的插件版本/浏览器/油猴管理器，比如：
0.3.45 / chrome / 篡改猴

**截图**
如果可以的话，尽量提供一些错误截图，比如控制台报错或者页面。

详见： https://linux.do/t/topic/216421

**Comment by QAbot-zh** [comment]
是不是这个更新引起的：[5e2456113993a1a66b5519a1c48b88f711752d25](https://github.com/dlzmoe/linuxdo-scripts/commit/5e2456113993a1a66b5519a1c48b88f711752d25)

**Comment by dlzmoe** [comment]
收到，我排查一下

**Comment by dlzmoe** [comment]
@QAbot-zh 0.3.46 还原了代码，暂时修复，后面我想一下解决办法。
