### ISSUE TITLE
【错误报告】等级查询错误。api 接错了？

### ISSUE THREAD

**Issue by Vitowong00** [dlzmoe/linuxdo-scripts#45]
**描述错误**

看帖子的回复，截图放在下面了。
https://linux.do/t/topic/218503/4

**版本说明**

0.3.48 / chrome / 暴力猴

**截图**

<img width="505" alt="image" src="https://github.com/user-attachments/assets/41d47e62-a001-4796-9a7a-b5456a2aa0cf">
<img width="378" alt="image" src="https://github.com/user-attachments/assets/e5b50fcc-c08d-42ed-9afc-45ebda7264e4">

**Comment by dlzmoe** [comment]
暂时无法解决，之前跟另外一个佬友讨论过，查询等级用的是设置中的数据，contact 数据没有暴露接口。两者的数据统计方式是不一样的，只能作为参考，你看打开偏好设置  https://linux.do/u/woaiRL/summary 这里的数据会跟等级查询一致。

![image](https://github.com/user-attachments/assets/4f924451-ba38-4b84-95eb-522da33997d9)
