### ISSUE TITLE
【功能请求】关于新版本检测

### ISSUE THREAD

**Issue by fangyuan99** [dlzmoe/linuxdo-scripts#47]
提出你的创意和功能想法，如果有参考的实现方法可以贴上链接。

现在直接跳转 [greasyfork](https://greasyfork.org/scripts/501827) 有点不太优雅，可以通过 https://api.github.com/repos/dlzmoe/linuxdo-scripts/releases/latest 接口里面的 tag_name 来判断

**Comment by dlzmoe** [comment]
这是个不错的建议，之后会修改
