### ISSUE TITLE
新标签页打开话题有几率会打开多个窗口

### ISSUE THREAD

**Issue by dlzmoe** [dlzmoe/linuxdo-scripts#5]
https://linux.do/t/topic/170951/142

多人反馈，mark 一下

**Comment by dlzmoe** [comment]
v0.1.4 优化此问题，观察一段时间，如果无问题再 close

**Comment by dzh213** [comment]
v0.1.8 仍然有此bug

**Comment by dlzmoe** [comment]
> v0.1.8 仍然有此bug

这个功能我重写一下，估计是哪里的逻辑出问题咯

**Comment by dzh213** [comment]
> > v0.1.8 仍然有此bug
> 
> 这个功能我重写一下，估计是哪里的逻辑出问题咯

不知道是否有缓存之类的，我浏览器确实一直没关，但是版本从v0.1.4升到了v0.1.8复现的概率还挺大

**Comment by dlzmoe** [comment]
@dzh213 我好绝望，这个功能我开启一周了，没出现打开多个标签页的情况，不只是你还有一个朋友给我反馈说一次打开多个

你用的什么浏览器呢？

**Comment by dzh213** [comment]
> @dzh213 我好绝望，这个功能我开启一周了，没出现打开多个标签页的情况，不只是你还有一个朋友给我反馈说一次打开多个
> 
> 你用的什么浏览器呢？

Chrome.  感觉和帖子有关系，一旦复现，同一个帖子多次打开必多窗口，但是刷新后，再打开就不会多个标签页了。

**Comment by dlzmoe** [comment]
@dzh213 我还需要更长时间去观察，现在主要是复现不了，不知道从哪里下手去修改 ~

**Comment by dlzmoe** [comment]
@dzh213 我好像发现了一个秘密，可以帮我测试下吗！！

在打开网站的始时候，在插件还没加载前迅速点击话题进入，然后返回上一页，再点击话题，看看是不是会打开多个？

**Comment by dzh213** [comment]
> @dzh213 我好像发现了一个秘密，可以帮我测试下吗！！
> 
> 在打开网站的时候，插件还没加载前迅速点击话题进入，然后返回上一页，再点击话题，看看是不是会打开多个？

是的，复现了。第一次进去因为插件没加载，所以不是新打开页面，退回去再次点击就多打开了。

**Comment by dlzmoe** [comment]
> > @dzh213 我好像发现了一个秘密，可以帮我测试下吗！！
> > 在打开网站的时候，插件还没加载前迅速点击话题进入，然后返回上一页，再点击话题，看看是不是会打开多个？
> 
> 是的，复现了。第一次进去因为插件没加载，所以不是新打开页面，退回去再次点击就多打开了。

那我知道问题所在了，等我修复一番

**Comment by dzh213** [comment]
当然场景上还有其他的case，比如我首页浏览下滑到加载下一页的帖子时，个别帖子也会多打开，但不是上面的那种立刻打开再退回去。

**Comment by dlzmoe** [comment]
> 当然场景上还有其他的case，比如我首页浏览下滑到加载下一页的帖子时，个别帖子也会多打开，但不是上面的那种立刻打开再退回去。

其原理都类似，我调整了逻辑实现方式，之前是监听出现新帖子时，将新标签页功能绑定上去，但是会有一个问题，就是旧帖子会重复绑定；现在是在触发事件时，先注销掉之前的事件重新绑定，不会出现重复的事件，实现方式更优雅了。

**Comment by dzh213** [comment]
> > 当然场景上还有其他的case，比如我首页浏览下滑到加载下一页的帖子时，个别帖子也会多打开，但不是上面的那种立刻打开再退回去。
> 
> 其原理都类似，我调整了逻辑实现方式，之前是监听出现新帖子时，将新标签页功能绑定上去，但是会有一个问题，就是旧帖子会重复绑定；现在是在触发事件时，先注销掉之前的事件重新绑定，不会出现重复的事件，实现方式更优雅了。
> 
> 试下 v0.1.10 版本

ok，我再观察下，有问题再给你反馈，感谢解决
