### ISSUE TITLE
【功能请求】自动滚动阅读添加后台不打断

### ISSUE THREAD

**Issue by DengYuncheng27** [dlzmoe/linuxdo-scripts#50]
最近就差浏览量就可以升3级了， 然后用到了这个功能。 
发现切换页面，或者最小化后， 任务暂停了。 (页面不在前台就暂停了)
应该是浏览器的问题， 但或许可以绕过，这样就可以挂后台了。

**Comment by dlzmoe** [comment]
这个跟浏览器的机制有关，切换标签页会使其他其他页面进入休眠，自动暂停默认滚动事件，我的解决方案拉出一个单独的窗口，同时不点击最小化，这时候使用其他软件不会影响滚动。
