### ISSUE TITLE
【功能请求】增加“禁用浏览帖子时URL更新楼层数”开关

### ISSUE THREAD

**Issue by closure11** [dlzmoe/linuxdo-scripts#57]
## 问题描述
论坛的帖子会在滚动到回复楼层时修改页面url，稍微浏览一会就会塞满浏览器历史记录，对我这样有些洁癖的用户不太友好

## 实现方式
From https://linux.do/t/topic/131216/18
```
require("discourse/routes/topic").default.disableReplaceState = true;
```

**Comment by dlzmoe** [comment]
这个不错，下个版本会加上。
