### ISSUE TITLE
【功能请求】增加一个总结所有评论的选项

### ISSUE THREAD

**Issue by Passerby1011** [dlzmoe/linuxdo-scripts#60]
提出你的创意和功能想法，如果有参考的实现方法可以贴上链接。
https://linux.do/t/topic/186528

**Comment by dlzmoe** [comment]
![image](https://github.com/user-attachments/assets/52141d8a-66ad-40ac-8f43-03209f572279)
这个佬很强，主要是获取全文数据这块我卡住了，所以没做这个功能，期待有更强的佬帮我完善一下。

**Comment by dlzmoe** [comment]
> 主要是现在的脚本界面易用性太差了，佬如果有能力可以合并进增强脚本了，把界面改的易用一点

他的算法加密了，我技术不行，搞不出来 😫

**Comment by Passerby1011** [comment]
> > 主要是现在的脚本界面易用性太差了，佬如果有能力可以合并进增强脚本了，把界面改的易用一点
> 
> 他的算法加密了，我技术不行，搞不出来 😫

悄悄的说一声，这个加密claude可以直接读

**Comment by dlzmoe** [comment]
这个很不错啊，我将会参考使用。

**Comment by CycleBai** [comment]
> ![image](https://private-user-images.githubusercontent.com/65840178/382148210-52141d8a-66ad-40ac-8f43-03209f572279.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDAxNjIsIm5iZiI6MTczMzI5OTg2MiwicGF0aCI6Ii82NTg0MDE3OC8zODIxNDgyMTAtNTIxNDFkOGEtNjZhZC00MGFjLThmNDMtMDMyMDlmNTcyMjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA4MTEwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YTdhMjE0ODg0OGVmMTNjYTU4NTYyMzkzZmExYWFlMDRmMzk2NTg0MmVmMWQ3Mjk0MjY5YzljOTc2MGI1Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uNRy2qERJTvahZ7QJJiccqWw0h_VkJV3b9zKBaIBQ48) 这个佬很强，主要是获取全文数据这块我卡住了，所以没做这个功能，期待有更强的佬帮我完善一下。

全文数据, 可以看一下 Discourse 的 API
GET 请求 https://linux.do/t/主题id.json 可以获取

**Comment by dlzmoe** [comment]
@CycleBai 这个接口只能获取前20条数据

**Comment by Passerby1011** [comment]
> @CycleBai 这个接口只能获取前20条数据
上面那个脚本的逻辑好像是逐层请求，规总后丢给ai
