### ISSUE TITLE
【错误报告】同步WebDav报错，Error creating folder

### ISSUE THREAD

**Issue by yidasanqian** [dlzmoe/linuxdo-scripts#65]
**描述错误**
同步到云端时，控制台报错Error creating folder: 
![image](https://github.com/user-attachments/assets/ea4fd86f-9d73-4672-83d0-299d81e918b5)

**版本说明**
Tampermonkey：5.1.1

**截图**
![image](https://github.com/user-attachments/assets/0f9ef440-597a-40a2-8f2d-4f7068b7806f)

**Comment by dlzmoe** [comment]
直接使用 `<域名>/dav/`  试试看呢，默认没有后缀，文件夹是程序自动生成的

**Comment by yidasanqian** [comment]
不行，我这是koofr 连接的OneDrive

**Comment by dlzmoe** [comment]
> 不行，我这是koofr 连接的OneDrive

要以 / 符号结尾，这个我刚试了 如果不带 / 会报错，如果还是不行，我回头得测试下OneDrive了，没用过这个存储，我平时webdav都是坚果云

**Comment by yidasanqian** [comment]
我加上后缀可以了  https://app.koofr.net/dav/OneDrive/linuxdo
![image](https://github.com/user-attachments/assets/bd3b460f-c8ec-467f-b34a-a6cb9537260f)
linuxdo目录好像不对，重复出现linuxdo

**Comment by yidasanqian** [comment]
> > 不行，我这是koofr 连接的OneDrive
> 
> 要以 / 符号结尾，这个我刚试了 如果不带 / 会报错，如果还是不行，我回头得测试下OneDrive了，没用过这个存储，我平时webdav都是坚果云

这是对的，谢谢你的回复
