### ISSUE TITLE
在edge浏览器下使用各个脚本管理器似乎会出现打不开的情况

### ISSUE THREAD

**Issue by dlzmoe** [dlzmoe/linuxdo-scripts#7]

**Comment by DIABLOOW** [comment]
我使用的edge+篡改猴，一切正常，可能跟浏览器版本或者其他插件有关

**Comment by dlzmoe** [comment]
> 我使用的edge+篡改猴，一切正常，可能跟浏览器版本或者其他插件有关

感谢使用！

我也是正常的，有部分伙伴反馈无法打开，我还在观察。
