### ISSUE TITLE
【💡 功能请求】希望帖子总结可以支持回复楼层和图片等

### ISSUE THREAD

**Issue by miaotouy** [dlzmoe/linuxdo-scripts#83]
### 描述你的功能需求

比如我整了个这样的预设，然后发现总结居然没带帖子中的回复楼层，只有楼主的信息。
而且在使用gemini等原生多模态模型时希望支持图片一起发。

![image](https://github.com/user-attachments/assets/1324b94a-10c7-42b0-942f-a534492b0039)

**Comment by dlzmoe** [comment]
https://github.com/dlzmoe/linuxdo-scripts/issues/60

跟这个需求一致，目前卡在获取全文信息上了，只能获取楼主的
