### ISSUE TITLE
【💡 功能请求】请求添加自定义css注入

### ISSUE THREAD

**Issue by stevessr** [dlzmoe/linuxdo-scripts#85]
### 描述你的功能需求

在主题风格中支持支持自定义css的添加
```javascipt
// 使用 GM_addStyle 注入 CSS 规则
```

**Comment by dlzmoe** [comment]
目前支持自定义css的

![image](https://github.com/user-attachments/assets/26aadd91-d45e-484f-9800-9c2352fab077)
