### ISSUE TITLE
请关闭具有页面侵入性质的浏览器插件后重试，如：油猴、迅雷等。

### ISSUE THREAD

**Issue by CangWeiohh** [dlzmoe/linuxdo-scripts#89]
### 你使用的浏览器 + 油猴管理器 + 插件版本

Chrome/油猴/0.4.9

### 描述错误

插件导致L站进不去, 请关闭具有页面侵入性质的浏览器插件后重试，如：油猴、迅雷等。

<img width="515" alt="image" src="https://github.com/user-attachments/assets/f11cc945-08a6-4026-b13e-3c57184291ff" />

**Comment by dlzmoe** [comment]
#86 如上，论坛提高了安全设置，禁止侵入式脚本修改DOM，最近在想办法解决

**Comment by dlzmoe** [comment]
#90
