### ISSUE TITLE
创建时间支持下显示之前年份

### ISSUE THREAD

**Issue by Leon406** [dlzmoe/linuxdo-scripts#9]
本年不显示年份，其他年份显示年份

脚本大部分功能可以用在其他discourse论坛

**Comment by dlzmoe** [comment]
> 本年不显示年份，其他年份显示年份

等到明年吧我测下这个功能 😎 linuxdo 论坛满打满算还没一年

> 脚本大部分功能可以用在其他discourse论坛

确实可以，因为代码都是基于 discourse 开发的

**Comment by Leon406** [comment]
建议脚本后缀改为 user.js， raw链接打开会自动请求安装更新

同时加下更新和下载链接，后续可以自动更新

可以参考下以下格式
// @updateURL    https://gitlab.com/xxx/jx.user.js
// @downloadURL  https://gitlab.com/xxx/jx.user.js

**Comment by dlzmoe** [comment]
> 建议脚本后缀改为 user.js， raw链接打开会自动请求安装更新
> 
> 同时加下更新和下载链接，后续可以自动更新
> 
> 可以参考下以下格式 // @updateURL https://gitlab.com/xxx/jx.user.js // @downloadurl https://gitlab.com/xxx/jx.user.js

这个可以有，我改一下

**Comment by dlzmoe** [comment]
@Leon406 试下这个链接，应该可以自动更新，raw 缓存 5 分钟左右

https://raw.githubusercontent.com/dlzmoe/linuxdo-scripts/main/linuxdo-scripts.user.js

**Comment by Leon406** [comment]
![image](https://github.com/user-attachments/assets/17b43da9-afde-4b3c-ab7b-ef031745eb8f)
其他网站使用图片不支持跨域

可以用github的资源及相关国内镜像

**Comment by dlzmoe** [comment]
可以的，回头我把资源链接都改改 @Leon406

**Comment by Leon406** [comment]
![image](https://github.com/user-attachments/assets/e8fb0cb2-6a06-4ef9-9ad2-b939c0eb08ed)

新版没有加非本年年份的显示，我先自己改了

混淆的文件大很多
![image](https://github.com/user-attachments/assets/08f0d539-6afe-4cad-ae3d-688cf4cb6ff9)

**Comment by dlzmoe** [comment]
@Leon406 
> 混淆的文件大很多

是的，因为打包文件带了很多依赖包，我也在想办法优化掉
