### ISSUE TITLE
（已有解决方案）有关脚本最近白屏被屏蔽的信息在这个Issues下讨论

### ISSUE THREAD

**Issue by dlzmoe** [dlzmoe/linuxdo-scripts#90]
### 你使用的浏览器 + 油猴管理器 + 插件版本

Chrome / 暴力猴 / 0.4.9

### 描述错误

论坛提高了安全设置，暂时无法绕过插入js脚本，在想办法解决了。
1. 改成浏览器扩展 （依旧禁止）
2. ...

**Comment by Twilight-9** [comment]
2. 向始皇施压（doge）：没有增强插件逛L站的动力都少了一半

**Comment by dlzmoe** [comment]
> 2. 向始皇施压（doge）：没有增强插件逛L站的动力都少了一半

倒反天罡了（doge）

**Comment by cakota6462** [comment]
@dlzmoe 现在不白屏了，但点设置按钮无反应

**Comment by dlzmoe** [comment]
1.0.0 解决这个问题，请安装浏览器扩展
