### ISSUE TITLE
【💡 功能请求】请求将设置按键自动隐藏。

### ISSUE THREAD

**Issue by Lyzd1** [dlzmoe/linuxdo-scripts#91]
### 描述你的功能需求

将设置这个大黑按键自动隐藏。鼠标悬停该位置后，才进行显示。感谢佬！

**Comment by dlzmoe** [comment]
下个版本会安排上，刚迁移过来很多细节还没打磨

**Comment by Lyzd1** [comment]
> 下个版本会安排上，刚迁移过来很多细节还没打磨

明白，佬 ，咱慢慢来。
