### ISSUE TITLE
【🐞 错误报告】

### ISSUE THREAD

**Issue by lcyan** [dlzmoe/linuxdo-scripts#92]
### 你使用的浏览器 + 油猴管理器 + 插件版本

chrome 1.0.1

### 描述错误

![image](https://github.com/user-attachments/assets/dd576494-fc67-4594-a68c-5ebd9655f19f)

**Comment by dlzmoe** [comment]
这个报错不影响使用，本地打包的扩展好像都会报这个

**Comment by 906051999** [comment]
> 这个报错不影响使用，本地打包的扩展好像都会报这个

启用了但是没有效果

**Comment by dlzmoe** [comment]
刷新页面，鼠标移动到最左侧也没有效果吗？

**Comment by lcyan** [comment]
有效果,看不到之前的配置⚙️了

**Comment by dlzmoe** [comment]
> 有效果,看不到之前的配置⚙️了

改过了，因为之前算是侵入式修改网站，被禁掉

**Comment by lcyan** [comment]
没问题了
