### ISSUE TITLE
【🐞 错误报告】

### ISSUE THREAD

**Issue by zrmomo** [dlzmoe/linuxdo-scripts#94]
### 你使用的浏览器版本 + 扩展插件版本号

版本 131.0.6778.205（正式版本） (arm64)

### 描述错误

![image](https://github.com/user-attachments/assets/7c2549e4-3e91-4e6d-8158-5c0a1101aa4e)

**Comment by dlzmoe** [comment]
这个报错不用管消不掉的，本地打包的扩展都会提示，不影响功能使用
